In [5]:
from nltk import PorterStemmer
Stemmer = PorterStemmer()

In [9]:
Stemmer.stem('Dancing')

'danc'

In [ ]:
from nltk import WordNetLemmatizer
Lemmetizer = WordNetLemmatizer()

In [11]:
Lemmetizer.lemmatize('Dancing')

'Dancing'

In [17]:
Paragraph = '''On 26 April 1986, the no. 4 reactor of the Chernobyl Nuclear Power Plant, located near Pripyat, Ukrainian SSR, Soviet Union (now Ukraine), exploded.[1] With dozens of direct casualties, it is one of only two nuclear energy accidents rated at the maximum severity on the International Nuclear Event Scale, the other being the 2011 Fukushima nuclear accident. The response involved more than 500,000 personnel and cost an estimated 18 billion rubles (about $84.5 billion USD in 2025).[2] It remains the worst nuclear disaster[3][4] and the most expensive disaster in history, with an estimated cost of US$700 billion.[5]

The disaster occurred while running a test to simulate cooling the reactor during an accident in blackout conditions. The operators carried out the test despite an accidental drop in reactor power, and due to a design issue, attempting to shut down the reactor in those conditions resulted in a dramatic power surge. The reactor components ruptured and lost coolant, and the resulting steam explosions and meltdown destroyed the reactor building. This was followed by a reactor core fire that spread radioactive contaminants across the Soviet Union and Europe.[6] A 10-kilometre (6.2 mi) exclusion zone was established 36 hours after the accident, initially evacuating around 49,000 people. The exclusion zone was later expanded to 30 kilometres (19 mi), resulting in the evacuation of approximately 68,000 more people.[7]

Following the explosion, which killed two engineers and severely burned two others, an emergency operation began to put out the fires and stabilize the reactor. Of the 237 workers hospitalized, 134 showed symptoms of acute radiation syndrome (ARS); 28 of them died within three months. Over the next decade, 14 more workers (nine of whom had ARS) died of various causes mostly unrelated to radiation exposure.[8] It is the only instance in commercial nuclear power history where radiation-related fatalities occurred.[9][10] As of 2005, 6000 cases of childhood thyroid cancer occurred within the affected populations (15 of them fatal), "a large fraction" being attributed to the disaster.[11] The United Nations Scientific Committee on the Effects of Atomic Radiation estimates fewer than 100 deaths have resulted from the fallout.[12] Predictions of the eventual total death toll vary; a 2006 World Health Organization study projected 9,000 cancer-related fatalities in Ukraine, Belarus, and Russia.[13]

Pripyat was abandoned and replaced by the purpose-built city of Slavutych. The Chernobyl Nuclear Power Plant sarcophagus, completed in December 1986, reduced the spread of radioactive contamination and provided radiological protection for the crews of the undamaged reactors. In 2016–2018, the Chernobyl New Safe Confinement was constructed around the old sarcophagus to enable the removal of the reactor debris, with clean-up scheduled for completion by 2065.[14]'''

In [63]:
Paragraph

'On 26 April 1986, the no. 4 reactor of the Chernobyl Nuclear Power Plant, located near Pripyat, Ukrainian SSR, Soviet Union (now Ukraine), exploded.[1] With dozens of direct casualties, it is one of only two nuclear energy accidents rated at the maximum severity on the International Nuclear Event Scale, the other being the 2011 Fukushima nuclear accident. The response involved more than 500,000 personnel and cost an estimated 18 billion rubles (about $84.5 billion USD in 2025).[2] It remains the worst nuclear disaster[3][4] and the most expensive disaster in history, with an estimated cost of US$700 billion.[5]\n\nThe disaster occurred while running a test to simulate cooling the reactor during an accident in blackout conditions. The operators carried out the test despite an accidental drop in reactor power, and due to a design issue, attempting to shut down the reactor in those conditions resulted in a dramatic power surge. The reactor components ruptured and lost coolant, and the resulting steam explosions and meltdown destroyed the reactor building. This was followed by a reactor core fire that spread radioactive contaminants across the Soviet Union and Europe.[6] A 10-kilometre (6.2 mi) exclusion zone was established 36 hours after the accident, initially evacuating around 49,000 people. The exclusion zone was later expanded to 30 kilometres (19 mi), resulting in the evacuation of approximately 68,000 more people.[7]\n\nFollowing the explosion, which killed two engineers and severely burned two others, an emergency operation began to put out the fires and stabilize the reactor. Of the 237 workers hospitalized, 134 showed symptoms of acute radiation syndrome (ARS); 28 of them died within three months. Over the next decade, 14 more workers (nine of whom had ARS) died of various causes mostly unrelated to radiation exposure.[8] It is the only instance in commercial nuclear power history where radiation-related fatalities occurred.[9][10] As of 2005, 6000 cases of childhood thyroid cancer occurred within the affected populations (15 of them fatal), "a large fraction" being attributed to the disaster.[11] The United Nations Scientific Committee on the Effects of Atomic Radiation estimates fewer than 100 deaths have resulted from the fallout.[12] Predictions of the eventual total death toll vary; a 2006 World Health Organization study projected 9,000 cancer-related fatalities in Ukraine, Belarus, and Russia.[13]\n\nPripyat was abandoned and replaced by the purpose-built city of Slavutych. The Chernobyl Nuclear Power Plant sarcophagus, completed in December 1986, reduced the spread of radioactive contamination and provided radiological protection for the crews of the undamaged reactors. In 2016–2018, the Chernobyl New Safe Confinement was constructed around the old sarcophagus to enable the removal of the reactor debris, with clean-up scheduled for completion by 2065.[14]'

In [64]:
import nltk

In [65]:
sentences = nltk.sent_tokenize(Paragraph)

In [66]:
sentences

['On 26 April 1986, the no.',
 '4 reactor of the Chernobyl Nuclear Power Plant, located near Pripyat, Ukrainian SSR, Soviet Union (now Ukraine), exploded.',
 '[1] With dozens of direct casualties, it is one of only two nuclear energy accidents rated at the maximum severity on the International Nuclear Event Scale, the other being the 2011 Fukushima nuclear accident.',
 'The response involved more than 500,000 personnel and cost an estimated 18 billion rubles (about $84.5 billion USD in 2025).',
 '[2] It remains the worst nuclear disaster[3][4] and the most expensive disaster in history, with an estimated cost of US$700 billion.',
 '[5]\n\nThe disaster occurred while running a test to simulate cooling the reactor during an accident in blackout conditions.',
 'The operators carried out the test despite an accidental drop in reactor power, and due to a design issue, attempting to shut down the reactor in those conditions resulted in a dramatic power surge.',
 'The reactor components ruptured and lost coolant, and the resulting steam explosions and meltdown destroyed the reactor building.',
 'This was followed by a reactor core fire that spread radioactive contaminants across the Soviet Union and Europe.',
 '[6] A 10-kilometre (6.2 mi) exclusion zone was established 36 hours after the accident, initially evacuating around 49,000 people.',
 'The exclusion zone was later expanded to 30 kilometres (19 mi), resulting in the evacuation of approximately 68,000 more people.',
 '[7]\n\nFollowing the explosion, which killed two engineers and severely burned two others, an emergency operation began to put out the fires and stabilize the reactor.',
 'Of the 237 workers hospitalized, 134 showed symptoms of acute radiation syndrome (ARS); 28 of them died within three months.',
 'Over the next decade, 14 more workers (nine of whom had ARS) died of various causes mostly unrelated to radiation exposure.',
 '[8] It is the only instance in commercial nuclear power history where radiation-related fatalities occurred.',
 '[9][10] As of 2005, 6000 cases of childhood thyroid cancer occurred within the affected populations (15 of them fatal), "a large fraction" being attributed to the disaster.',
 '[11] The United Nations Scientific Committee on the Effects of Atomic Radiation estimates fewer than 100 deaths have resulted from the fallout.',
 '[12] Predictions of the eventual total death toll vary; a 2006 World Health Organization study projected 9,000 cancer-related fatalities in Ukraine, Belarus, and Russia.',
 '[13]\n\nPripyat was abandoned and replaced by the purpose-built city of Slavutych.',
 'The Chernobyl Nuclear Power Plant sarcophagus, completed in December 1986, reduced the spread of radioactive contamination and provided radiological protection for the crews of the undamaged reactors.',
 'In 2016–2018, the Chernobyl New Safe Confinement was constructed around the old sarcophagus to enable the removal of the reactor debris, with clean-up scheduled for completion by 2065.',
 '[14]']

In [73]:
from nltk.corpus import stopwords

In [67]:
import re

In [83]:
corpus = []

for i, item in enumerate(sentences):
    review = re.sub('[^a-zA-Z]',' ',item)
    review = review.lower()
    review = review.split()
    review = [Lemmetizer.lemmatize(word) for word in review if word not in set(stopwords.words('English'))]
    review = ' '.join(review)    
    corpus.append(review)

In [84]:
corpus

['april',
 'reactor chernobyl nuclear power plant located near pripyat ukrainian ssr soviet union ukraine exploded',
 'dozen direct casualty one two nuclear energy accident rated maximum severity international nuclear event scale fukushima nuclear accident',
 'response involved personnel cost estimated billion ruble billion usd',
 'remains worst nuclear disaster expensive disaster history estimated cost u billion',
 'disaster occurred running test simulate cooling reactor accident blackout condition',
 'operator carried test despite accidental drop reactor power due design issue attempting shut reactor condition resulted dramatic power surge',
 'reactor component ruptured lost coolant resulting steam explosion meltdown destroyed reactor building',
 'followed reactor core fire spread radioactive contaminant across soviet union europe',
 'kilometre mi exclusion zone established hour accident initially evacuating around people',
 'exclusion zone later expanded kilometre mi resulting evacuation approximately people',
 'following explosion killed two engineer severely burned two others emergency operation began put fire stabilize reactor',
 'worker hospitalized showed symptom acute radiation syndrome ar died within three month',
 'next decade worker nine ar died various cause mostly unrelated radiation exposure',
 'instance commercial nuclear power history radiation related fatality occurred',
 'case childhood thyroid cancer occurred within affected population fatal large fraction attributed disaster',
 'united nation scientific committee effect atomic radiation estimate fewer death resulted fallout',
 'prediction eventual total death toll vary world health organization study projected cancer related fatality ukraine belarus russia',
 'pripyat abandoned replaced purpose built city slavutych',
 'chernobyl nuclear power plant sarcophagus completed december reduced spread radioactive contamination provided radiological protection crew undamaged reactor',
 'chernobyl new safe confinement constructed around old sarcophagus enable removal reactor debris clean scheduled completion',
 '']

In [47]:
lemm = []
for i in corpus:
    words = nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('English')):
            print(Lemmetizer.lemmatize(word))

april
reactor
chernobyl
nuclear
power
plant
located
near
pripyat
ukrainian
ssr
soviet
union
ukraine
exploded
dozen
direct
casualty
one
two
nuclear
energy
accident
rated
maximum
severity
international
nuclear
event
scale
fukushima
nuclear
accident
response
involved
personnel
cost
estimated
billion
ruble
billion
usd
remains
worst
nuclear
disaster
expensive
disaster
history
estimated
cost
u
billion
disaster
occurred
running
test
simulate
cooling
reactor
accident
blackout
condition
operator
carried
test
despite
accidental
drop
reactor
power
due
design
issue
attempting
shut
reactor
condition
resulted
dramatic
power
surge
reactor
component
ruptured
lost
coolant
resulting
steam
explosion
meltdown
destroyed
reactor
building
followed
reactor
core
fire
spread
radioactive
contaminant
across
soviet
union
europe
kilometre
mi
exclusion
zone
established
hour
accident
initially
evacuating
around
people
exclusion
zone
later
expanded
kilometre
mi
resulting
evacuation
approximately
people
following
explosion
killed
two
engineer
severely
burned
two
others
emergency
operation
began
put
fire
stabilize
reactor
worker
hospitalized
showed
symptom
acute
radiation
syndrome
ar
died
within
three
month
next
decade
worker
nine
ar
died
various
cause
mostly
unrelated
radiation
exposure
instance
commercial
nuclear
power
history
radiation
related
fatality
occurred
case
childhood
thyroid
cancer
occurred
within
affected
population
fatal
large
fraction
attributed
disaster
united
nation
scientific
committee
effect
atomic
radiation
estimate
fewer
death
resulted
fallout
prediction
eventual
total
death
toll
vary
world
health
organization
study
projected
cancer
related
fatality
ukraine
belarus
russia
pripyat
abandoned
replaced
purpose
built
city
slavutych
chernobyl
nuclear
power
plant
sarcophagus
completed
december
reduced
spread
radioactive
contamination
provided
radiological
protection
crew
undamaged
reactor
chernobyl
new
safe
confinement
constructed
around
old
sarcophagus
enable
removal
reactor
debris
clean
scheduled
completion

In [85]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [90]:
X = cv.fit_transform(corpus)

In [101]:
cv.vocabulary_

{'april': 7,
 'reactor': 135,
 'chernobyl': 25,
 'nuclear': 111,
 'power': 123,
 'plant': 121,
 'located': 99,
 'near': 107,
 'pripyat': 125,
 'ukrainian': 175,
 'ssr': 161,
 'soviet': 159,
 'union': 177,
 'ukraine': 174,
 'exploded': 74,
 'dozen': 54,
 'direct': 52,
 'casualty': 23,
 'one': 114,
 'two': 173,
 'energy': 61,
 'accident': 1,
 'rated': 134,
 'maximum': 101,
 'severity': 154,
 'international': 92,
 'event': 69,
 'scale': 150,
 'fukushima': 85,
 'response': 141,
 'involved': 93,
 'personnel': 120,
 'cost': 42,
 'estimated': 65,
 'billion': 15,
 'ruble': 144,
 'usd': 180,
 'remains': 138,
 'worst': 186,
 'disaster': 53,
 'expensive': 73,
 'history': 87,
 'occurred': 112,
 'running': 145,
 'test': 168,
 'simulate': 157,
 'cooling': 40,
 'blackout': 16,
 'condition': 34,
 'operator': 116,
 'carried': 21,
 'despite': 49,
 'accidental': 2,
 'drop': 56,
 'due': 57,
 'design': 48,
 'issue': 94,
 'attempting': 11,
 'shut': 156,
 'resulted': 142,
 'dramatic': 55,
 'surge': 165,
 'component': 33,
 'ruptured': 146,
 'lost': 100,
 'coolant': 39,
 'resulting': 143,
 'steam': 163,
 'explosion': 75,
 'meltdown': 102,
 'destroyed': 50,
 'building': 17,
 'followed': 82,
 'core': 41,
 'fire': 81,
 'spread': 160,
 'radioactive': 132,
 'contaminant': 37,
 'across': 3,
 'europe': 66,
 'kilometre': 96,
 'mi': 103,
 'exclusion': 71,
 'zone': 187,
 'established': 63,
 'hour': 89,
 'initially': 90,
 'evacuating': 67,
 'around': 9,
 'people': 119,
 'later': 98,
 'expanded': 72,
 'evacuation': 68,
 'approximately': 6,
 'following': 83,
 'killed': 95,
 'engineer': 62,
 'severely': 153,
 'burned': 19,
 'others': 118,
 'emergency': 59,
 'operation': 115,
 'began': 13,
 'put': 130,
 'stabilize': 162,
 'worker': 184,
 'hospitalized': 88,
 'showed': 155,
 'symptom': 166,
 'acute': 4,
 'radiation': 131,
 'syndrome': 167,
 'ar': 8,
 'died': 51,
 'within': 183,
 'three': 169,
 'month': 104,
 'next': 109,
 'decade': 46,
 'nine': 110,
 'various': 181,
 'cause': 24,
 'mostly': 105,
 'unrelated': 179,
 'exposure': 76,
 'instance': 91,
 'commercial': 29,
 'related': 137,
 'fatality': 79,
 'case': 22,
 'childhood': 26,
 'thyroid': 170,
 'cancer': 20,
 'affected': 5,
 'population': 122,
 'fatal': 78,
 'large': 97,
 'fraction': 84,
 'attributed': 12,
 'united': 178,
 'nation': 106,
 'scientific': 152,
 'committee': 30,
 'effect': 58,
 'atomic': 10,
 'estimate': 64,
 'fewer': 80,
 'death': 44,
 'fallout': 77,
 'prediction': 124,
 'eventual': 70,
 'total': 172,
 'toll': 171,
 'vary': 182,
 'world': 185,
 'health': 86,
 'organization': 117,
 'study': 164,
 'projected': 126,
 'belarus': 14,
 'russia': 147,
 'abandoned': 0,
 'replaced': 140,
 'purpose': 129,
 'built': 18,
 'city': 27,
 'slavutych': 158,
 'sarcophagus': 149,
 'completed': 31,
 'december': 47,
 'reduced': 136,
 'contamination': 38,
 'provided': 128,
 'radiological': 133,
 'protection': 127,
 'crew': 43,
 'undamaged': 176,
 'new': 108,
 'safe': 148,
 'confinement': 35,
 'constructed': 36,
 'old': 113,
 'enable': 60,
 'removal': 139,
 'debris': 45,
 'clean': 28,
 'scheduled': 151,
 'completion': 32}

In [102]:
corpus[0]

'april'

In [103]:
X[0].toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [104]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(ngram_range=(1,2))

In [105]:
X = tfidf.fit_transform(corpus)

In [107]:
tfidf.get_feature_names_out()

array(['abandoned', 'abandoned replaced', 'accident', 'accident blackout',
       'accident initially', 'accident rated', 'accidental',
       'accidental drop', 'across', 'across soviet', 'acute',
       'acute radiation', 'affected', 'affected population',
       'approximately', 'approximately people', 'april', 'ar', 'ar died',
       'around', 'around old', 'around people', 'atomic',
       'atomic radiation', 'attempting', 'attempting shut', 'attributed',
       'attributed disaster', 'began', 'began put', 'belarus',
       'belarus russia', 'billion', 'billion ruble', 'billion usd',
       'blackout', 'blackout condition', 'building', 'built',
       'built city', 'burned', 'burned two', 'cancer', 'cancer occurred',
       'cancer related', 'carried', 'carried test', 'case',
       'case childhood', 'casualty', 'casualty one', 'cause',
       'cause mostly', 'chernobyl', 'chernobyl new', 'chernobyl nuclear',
       'childhood', 'childhood thyroid', 'city', 'city slavutych',
       'clean', 'clean scheduled', 'commercial', 'commercial nuclear',
       'committee', 'committee effect', 'completed', 'completed december',
       'completion', 'component', 'component ruptured', 'condition',
       'condition resulted', 'confinement', 'confinement constructed',
       'constructed', 'constructed around', 'contaminant',
       'contaminant across', 'contamination', 'contamination provided',
       'coolant', 'coolant resulting', 'cooling', 'cooling reactor',
       'core', 'core fire', 'cost', 'cost billion', 'cost estimated',
       'crew', 'crew undamaged', 'death', 'death resulted', 'death toll',
       'debris', 'debris clean', 'decade', 'decade worker', 'december',
       'december reduced', 'design', 'design issue', 'despite',
       'despite accidental', 'destroyed', 'destroyed reactor', 'died',
       'died various', 'died within', 'direct', 'direct casualty',
       'disaster', 'disaster expensive', 'disaster history',
       'disaster occurred', 'dozen', 'dozen direct', 'dramatic',
       'dramatic power', 'drop', 'drop reactor', 'due', 'due design',
       'effect', 'effect atomic', 'emergency', 'emergency operation',
       'enable', 'enable removal', 'energy', 'energy accident',
       'engineer', 'engineer severely', 'established', 'established hour',
       'estimate', 'estimate fewer', 'estimated', 'estimated billion',
       'estimated cost', 'europe', 'evacuating', 'evacuating around',
       'evacuation', 'evacuation approximately', 'event', 'event scale',
       'eventual', 'eventual total', 'exclusion', 'exclusion zone',
       'expanded', 'expanded kilometre', 'expensive',
       'expensive disaster', 'exploded', 'explosion', 'explosion killed',
       'explosion meltdown', 'exposure', 'fallout', 'fatal',
       'fatal large', 'fatality', 'fatality occurred', 'fatality ukraine',
       'fewer', 'fewer death', 'fire', 'fire spread', 'fire stabilize',
       'followed', 'followed reactor', 'following', 'following explosion',
       'fraction', 'fraction attributed', 'fukushima',
       'fukushima nuclear', 'health', 'health organization', 'history',
       'history estimated', 'history radiation', 'hospitalized',
       'hospitalized showed', 'hour', 'hour accident', 'initially',
       'initially evacuating', 'instance', 'instance commercial',
       'international', 'international nuclear', 'involved',
       'involved personnel', 'issue', 'issue attempting', 'killed',
       'killed two', 'kilometre', 'kilometre mi', 'large',
       'large fraction', 'later', 'later expanded', 'located',
       'located near', 'lost', 'lost coolant', 'maximum',
       'maximum severity', 'meltdown', 'meltdown destroyed', 'mi',
       'mi exclusion', 'mi resulting', 'month', 'mostly',
       'mostly unrelated', 'nation', 'nation scientific', 'near',
       'near pripyat', 'new', 'new safe', 'next', 'next decade', 'nine',
       'nine ar', 'nuclear', 'nuclear accident', 'nuclear disaster',
       'nuclear energy', 'nuclear event', 'nuclear power', 'occurred',
       'occurred running', 'occurred within', 'old', 'old sarcophagus',
       'one', 'one two', 'operation', 'operation began', 'operator',
       'operator carried', 'organization', 'organization study', 'others',
       'others emergency', 'people', 'personnel', 'personnel cost',
       'plant', 'plant located', 'plant sarcophagus', 'population',
       'population fatal', 'power', 'power due', 'power history',
       'power plant', 'power surge', 'prediction', 'prediction eventual',
       'pripyat', 'pripyat abandoned', 'pripyat ukrainian', 'projected',
       'projected cancer', 'protection', 'protection crew', 'provided',
       'provided radiological', 'purpose', 'purpose built', 'put',
       'put fire', 'radiation', 'radiation estimate',
       'radiation exposure', 'radiation related', 'radiation syndrome',
       'radioactive', 'radioactive contaminant',
       'radioactive contamination', 'radiological',
       'radiological protection', 'rated', 'rated maximum', 'reactor',
       'reactor accident', 'reactor building', 'reactor chernobyl',
       'reactor component', 'reactor condition', 'reactor core',
       'reactor debris', 'reactor power', 'reduced', 'reduced spread',
       'related', 'related fatality', 'remains', 'remains worst',
       'removal', 'removal reactor', 'replaced', 'replaced purpose',
       'response', 'response involved', 'resulted', 'resulted dramatic',
       'resulted fallout', 'resulting', 'resulting evacuation',
       'resulting steam', 'ruble', 'ruble billion', 'running',
       'running test', 'ruptured', 'ruptured lost', 'russia', 'safe',
       'safe confinement', 'sarcophagus', 'sarcophagus completed',
       'sarcophagus enable', 'scale', 'scale fukushima', 'scheduled',
       'scheduled completion', 'scientific', 'scientific committee',
       'severely', 'severely burned', 'severity',
       'severity international', 'showed', 'showed symptom', 'shut',
       'shut reactor', 'simulate', 'simulate cooling', 'slavutych',
       'soviet', 'soviet union', 'spread', 'spread radioactive', 'ssr',
       'ssr soviet', 'stabilize', 'stabilize reactor', 'steam',
       'steam explosion', 'study', 'study projected', 'surge', 'symptom',
       'symptom acute', 'syndrome', 'syndrome ar', 'test', 'test despite',
       'test simulate', 'three', 'three month', 'thyroid',
       'thyroid cancer', 'toll', 'toll vary', 'total', 'total death',
       'two', 'two engineer', 'two nuclear', 'two others', 'ukraine',
       'ukraine belarus', 'ukraine exploded', 'ukrainian',
       'ukrainian ssr', 'undamaged', 'undamaged reactor', 'union',
       'union europe', 'union ukraine', 'united', 'united nation',
       'unrelated', 'unrelated radiation', 'usd', 'various',
       'various cause', 'vary', 'vary world', 'within', 'within affected',
       'within three', 'worker', 'worker hospitalized', 'worker nine',
       'world', 'world health', 'worst', 'worst nuclear', 'zone',
       'zone established', 'zone later'], dtype=object)

In [106]:
X[0].toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [108]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-win_amd64.whl.metadata (8.6 kB)
Requirement already satisfied: numpy>=1.18.5 in c:\desktop\python\venv\lib\site-packages (from gensim) (2.3.2)
Requirement already satisfied: scipy>=1.7.0 in c:\desktop\python\venv\lib\site-packages (from gensim) (1.16.2)
Collecting smart_open>=1.8.1 (from gensim)
  Downloading smart_open-7.4.1-py3-none-any.whl.metadata (24 kB)
Collecting wrapt (from smart_open>=1.8.1->gensim)
  Downloading wrapt-2.0.0-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Downloading gensim-4.4.0-cp312-cp312-win_amd64.whl (24.4 MB)
   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   - -------------------------------------- 1.0/24.4 MB 16.7 MB/s eta 0:00:02
   - -------------------------------------- 1.0/24.4 MB 16.7 MB/s eta 0:00:02
   - -------------------------------------- 1.0/24.4 MB 16.7 MB/s eta 0:00:02
   - -------------------------------------- 1.0/24.4 MB 16.7 MB/s eta 0:00:02
   -- ------------------------------------- 1.6/24.4 MB 1.2 MB/s eta 0:00:19
   ------- -------------------------------- 4.7/24.4 MB 3.5 MB/s eta 0:00:06
   ------------- -------------------------- 8.1/24.4 MB 5.3 MB/s eta 0:00:04
   ------------------- -------------------- 11.8/24.4 MB 6.7 MB/s eta 0:00:02
   ------------------------ --------------- 14.7/24.4 MB 7.6 MB/s eta 0:00:02
   ------------------------ --------------- 14.9/24.4 MB 6.9 MB/s eta 0:00:02
   ------------------------------ --------- 18.9/24.4 MB 7.9 MB/s eta 0:00:01
   --------------------------------- ------ 20.4/24.4 MB 7.8 MB/s eta 0:00:01
   -------------------------------------- - 23.3/24.4 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 24.4/24.4 MB 8.3 MB/s eta 0:00:00
Downloading smart_open-7.4.1-py3-none-any.whl (63 kB)
Downloading wrapt-2.0.0-cp312-cp312-win_amd64.whl (60 kB)
Installing collected packages: wrapt, smart_open, gensim
Successfully installed gensim-4.4.0 smart_open-7.4.1 wrapt-2.0.0

In [109]:
from gensim.models import word2vec, keyedvectors

In [110]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vec_king = wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded

In [111]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  2.01416016e-02, -1.63085938e-01,  1.35803223e-03,
       -1.44531250e-01, -5.68847656e-02,  4.29687500e-02, -2.46582031e-02,
        1.85546875e-01,  4.47265625e-01,  9.58251953e-03,  1.31835938e-01,
        9.86328125e-02, -1.85546875e-01, -1.00097656e-01, -1.33789062e-01,
       -1.25000000e-01,  2.83203125e-01,  1.23046875e-01,  5.32226562e-02,
       -1.77734375e-01,  8.59375000e-02, -2.18505859e-02,  2.05078125e-02,
       -1.39648438e-01,  2.51464844e-02,  1.38671875e-01, -1.05468750e-01,
        1.38671875e-01,  8.88671875e-02, -7.51953125e-02, -2.13623047e-02,
        1.72851562e-01,  4.63867188e-02, -2.65625000e-01,  8.91113281e-03,
        1.49414062e-01,  3.78417969e-02,  2.38281250e-01, -1.24511719e-01,
       -2.17773438e-01, -1.81640625e-01,  2.97851562e-02,  5.71289062e-02,
       -2.89306641e-02,  1.24511719e-02,  9.66796875e-02, -2.31445312e-01,
        5.81054688e-02,  6.68945312e-02,  7.08007812e-02, -3.08593750e-01,
       -2.14843750e-01,  1.45507812e-01, -4.27734375e-01, -9.39941406e-03,
        1.54296875e-01, -7.66601562e-02,  2.89062500e-01,  2.77343750e-01,
       -4.86373901e-04, -1.36718750e-01,  3.24218750e-01, -2.46093750e-01,
       -3.03649902e-03, -2.11914062e-01,  1.25000000e-01,  2.69531250e-01,
        2.04101562e-01,  8.25195312e-02, -2.01171875e-01, -1.60156250e-01,
       -3.78417969e-02, -1.20117188e-01,  1.15234375e-01, -4.10156250e-02,
       -3.95507812e-02, -8.98437500e-02,  6.34765625e-03,  2.03125000e-01,
        1.86523438e-01,  2.73437500e-01,  6.29882812e-02,  1.41601562e-01,
       -9.81445312e-02,  1.38671875e-01,  1.82617188e-01,  1.73828125e-01,
        1.73828125e-01, -2.37304688e-01,  1.78710938e-01,  6.34765625e-02,
        2.36328125e-01, -2.08984375e-01,  8.74023438e-02, -1.66015625e-01,
       -7.91015625e-02,  2.43164062e-01, -8.88671875e-02,  1.26953125e-01,
       -2.16796875e-01, -1.73828125e-01, -3.59375000e-01, -8.25195312e-02,
       -6.49414062e-02,  5.07812500e-02,  1.35742188e-01, -7.47070312e-02,
       -1.64062500e-01,  1.15356445e-02,  4.45312500e-01, -2.15820312e-01,
       -1.11328125e-01, -1.92382812e-01,  1.70898438e-01, -1.25000000e-01,
        2.65502930e-03,  1.92382812e-01, -1.74804688e-01,  1.39648438e-01,
        2.92968750e-01,  1.13281250e-01,  5.95703125e-02, -6.39648438e-02,
        9.96093750e-02, -2.72216797e-02,  1.96533203e-02,  4.27246094e-02,
       -2.46093750e-01,  6.39648438e-02, -2.25585938e-01, -1.68945312e-01,
        2.89916992e-03,  8.20312500e-02,  3.41796875e-01,  4.32128906e-02,
        1.32812500e-01,  1.42578125e-01,  7.61718750e-02,  5.98144531e-02,
       -1.19140625e-01,  2.74658203e-03, -6.29882812e-02, -2.72216797e-02,
       -4.82177734e-03, -8.20312500e-02, -2.49023438e-02, -4.00390625e-01,
       -1.06933594e-01,  4.24804688e-02,  7.76367188e-02, -1.16699219e-01,
        7.37304688e-02, -9.22851562e-02,  1.07910156e-01,  1.58203125e-01,
        4.24804688e-02,  1.26953125e-01,  3.61328125e-02,  2.67578125e-01,
       -1.01074219e-01, -3.02734375e-01, -5.76171875e-02,  5.05371094e-02,
        5.26428223e-04, -2.07031250e-01, -1.38671875e-01, -8.97216797e-03,
       -2.78320312e-02, -1.41601562e-01,  2.07031250e-01, -1.58203125e-01,
        1.27929688e-01,  1.49414062e-01, -2.24609375e-02, -8.44726562e-02,
        1.22558594e-01,  2.15820312e-01, -2.13867188e-01, -3.12500000e-01,
       -3.73046875e-01,  4.08935547e-03,  1.07421875e-01,  1.06933594e-01,
        7.32421875e-02,  8.97216797e-03, -3.88183594e-02, -1.29882812e-01,
        1.49414062e-01, -2.14843750e-01, -1.83868408e-03,  9.91210938e-02,
        1.57226562e-01, -1.14257812e-01, -2.05078125e-01,  9.91210938e-02,
        3.69140625e-01, -1.97265625e-01,  3.54003906e-02,  1.09375000e-01,
        1.31835938e-01,  1.66992188e-01,  2.35351562e-01,  1.04980469e-01,
       -4.96093750e-01, -1.64062500e-01, -1.56250000e-01, -5.22460938e-02,
        1.03027344e-01,  2.43164062e-01, -1.88476562e-01,  5.07812500e-02,
       -9.37500000e-02, -6.68945312e-02,  2.27050781e-02,  7.61718750e-02,
        2.89062500e-01,  3.10546875e-01, -5.37109375e-02,  2.28515625e-01,
        2.51464844e-02,  6.78710938e-02, -1.21093750e-01, -2.15820312e-01,
       -2.73437500e-01, -3.07617188e-02, -3.37890625e-01,  1.53320312e-01,
        2.33398438e-01, -2.08007812e-01,  3.73046875e-01,  8.20312500e-02,
        2.51953125e-01, -7.61718750e-02, -4.66308594e-02, -2.23388672e-02,
        2.99072266e-02, -5.93261719e-02, -4.66918945e-03, -2.44140625e-01,
       -2.09960938e-01, -2.87109375e-01, -4.54101562e-02, -1.77734375e-01,
       -2.79296875e-01, -8.59375000e-02,  9.13085938e-02,  2.51953125e-01],
      dtype=float32)

In [114]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [115]:
wv.similarity('hockey','sports')

np.float32(0.53541523)

In [117]:
vec = wv['king']-wv['man']+wv['woman']

In [118]:
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [130]:
## imprting the dataset

import pandas as pd

messages = pd.read_csv(r'C:\Users\KIIT\Downloads\NLP-Live-main\NLP-Live-main\smsspamcollection\SMSSpamCollection', sep='\t',names=["label", "message"])

In [131]:
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.read_csv('matches - matches.csv')

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN