## What is Series
#### A series is a one-dimensional labelled array. [Think of it as a single cloumn in excel]

In [2]:
import pandas as pd

In [ ]:
## Creating a Series 

## From List
s = pd.Series(["a","b","c","d"],index=[1,2,3,4])
print(s)

1    a
2    b
3    c
4    d
dtype: object

In [10]:
#### Access Value

display(s[1])
display(s[4])

'a'

'd'

In [12]:
## From dictionary

d = pd.Series({1:'a',2:'b',3:'c'})
print(d)

1    a
2    b
3    c
dtype: object

In [ ]:
## Series Properties

print(type((s.values)))     ## <class 'numpy.ndarray'> [returns numpy array ]
type(list(s.values))        ## converted to list


print(type((s.index)))     ## <class 'pandas.core.indexes.base.Index'>
type(list(s.index))        ## converted to list

s.dtype        ## Doubt 

s.shape

<class 'numpy.ndarray'>
<class 'pandas.core.indexes.base.Index'>

(4,)

## What is DataFrame?

#### A DataFrame is a two-dimensional table [Think of it like an excel sheet or SQL table]

In [25]:
data = {
    'name': ['A','B','C','D'],      ## All arrays must be of the same length, or throws value error
    'age': [2,4,5,6]
}

df = pd.DataFrame(data)

print(df)

  name  age
0    A    2
1    B    4
2    C    5
3    D    6

In [27]:
## Creating DataFrame 

## From Dictionary

df_data = {
    'name':['A','B'],
    'age': [1,2]
}

df = pd.DataFrame(df_data)

df

  name  age
0    A    1
1    B    2

In [ ]:
## From List of Lists

df_ListOfLists_data = [
    ['Name','Age'],
    ['A',1]
]

df = pd.DataFrame(df_ListOfLists_data)

df

      0    1
0  Name  Age
1     A    1

In [ ]:

df_ListOfLists_data = [
    ['B',2],
    ['A',1]
]

df = pd.DataFrame(df_ListOfLists_data,columns=['Name','Age'])       ## Custom Column

df

  Name  Age
0    B    2
1    A    1

In [33]:
## List of Dictionaries

df_listofDictionaries_data =[
    {
        'Name': 'A',
        'Age' : 1
    },
    {
        'Name': 'B',
        'Age' : 2
    },
]

df = pd.DataFrame(df_listofDictionaries_data)

df

  Name  Age
0    A    1
1    B    2

In [34]:
## Accessing DataFrame Columns

df['Age']

0    1
1    2
Name: Age, dtype: int64

In [35]:
## Multiple Column

df[['Name','Age']]

  Name  Age
0    A    1
1    B    2

In [41]:
## DataFrame Properties

# df.shape

# df.columns

# type(df.columns)

df.index

df.dtypes

Name    object
Age      int64
dtype: object

| Feature   | Series        | DataFrame |
| --------- | ------------- | --------- |
| Dimension | 1D            | 2D        |
| Structure | single column | table     |
| Index     | yes           | yes       |
| Columns   | no            | yes       |

## Indexing

In [42]:
df

  Name  Age
0    A    1
1    B    2

In [ ]:
df.loc[0].shape

(2,)

In [ ]:
df.iloc[0]      ## iloc → Position Based Indexing

Name    A
Age     1
Name: 0, dtype: object

In [46]:
df.index = [10,20]
df

   Name  Age
10    A    1
20    B    2

In [ ]:
df.loc[10]      ## Label Based Indexing

Name    A
Age     1
Name: 10, dtype: object

In [49]:
df.iloc[0]

Name    A
Age     1
Name: 10, dtype: object

In [50]:
df.index = ['a','b']

In [51]:
df

  Name  Age
a    A    1
b    B    2

In [54]:
df.loc['a']

Name    A
Age     1
Name: a, dtype: object

In [55]:
df.iloc[0]

Name    A
Age     1
Name: a, dtype: object

In [56]:
df = pd.DataFrame({
    "name":["A","B","C"],
    "age":[25,30,22],
    "city":["NY","LA","SF"]
})

In [57]:
df

  name  age city
0    A   25   NY
1    B   30   LA
2    C   22   SF

In [58]:
df.loc[0,'name']

'A'

In [60]:
df.loc[0:2,['name','age']]

  name  age
0    A   25
1    B   30
2    C   22

In [62]:
# .loc[] → label-based; 0:2 means rows labeled 0, 1, 2 (inclusive)
# .iloc[] → integer position-based; 0:2 means positions 0, 1 (exclusive of 2)

df.iloc[0:2,0:2]

  name  age
0    A   25
1    B   30

In [64]:
# loc → labels
# iloc → integers

df.index = [10,20,30]

df

   name  age city
10    A   25   NY
20    B   30   LA
30    C   22   SF

In [66]:
df.loc[10:30,['name','age']]

   name  age
10    A   25
20    B   30
30    C   22

In [71]:
df.loc[10:30,:]

   name  age city
10    A   25   NY
20    B   30   LA
30    C   22   SF

In [72]:
df.loc[[10,30],['name','city']]

   name city
10    A   NY
30    C   SF

In [75]:
df.iloc[[0,2],[0,2]]

   name city
10    A   NY
30    C   SF

## 🧠 Practice Questions

##### Use this DataFrame:

In [77]:
df = pd.DataFrame({
"name":["A","B","C","D"],
"age":[25,30,22,28],
"salary":[5000,6000,4500,7000]
})
df

  name  age  salary
0    A   25    5000
1    B   30    6000
2    C   22    4500
3    D   28    7000

In [78]:
## Select first row using iloc

df.iloc[0]

name         A
age         25
salary    5000
Name: 0, dtype: object

In [81]:
## Select name column using loc

df.loc[:,'name']

0    A
1    B
2    C
3    D
Name: name, dtype: object

In [86]:
## Select age of row 2

display(df.loc[2,'age'])

display(df.iloc[2,1])

np.int64(22)

np.int64(22)

In [89]:
## Select first 2 rows and first 2 columns

display(df.loc[0:1,['name','age']])

df.iloc[0:2,0:2]

  name  age
0    A   25
1    B   30

  name  age
0    A   25
1    B   30

In [90]:
## Filter employees where salary > 5000

df[df['salary']>5000]

  name  age  salary
1    B   30    6000
3    D   28    7000

## 🧠 Mini Challenge

## Predict the output before running:

In [92]:
df = pd.DataFrame({
"A":[10,20,30],
"B":[1,2,3]
})

df

    A  B
0  10  1
1  20  2
2  30  3

In [93]:
print(df.iloc[:,0])

0    10
1    20
2    30
Name: A, dtype: int64

## Lesson 3 — Boolean Indexing & Filtering

### 1️⃣ What is Boolean Indexing?

### Boolean indexing means filtering rows using conditions.

In [94]:
df = pd.DataFrame({
"name":["A","B","C","D"],
"age":[25,30,22,28],
"salary":[5000,6000,4500,7000]
})

df

  name  age  salary
0    A   25    5000
1    B   30    6000
2    C   22    4500
3    D   28    7000

In [95]:
df["salary"] > 5000

0    False
1     True
2    False
3     True
Name: salary, dtype: bool

In [97]:
## This is a Boolean Series.

## Now apply it to the DataFrame.

df[df["salary"] > 5000]

  name  age  salary
1    B   30    6000
3    D   28    7000

In [98]:
## Filtering with Multiple Conditions

## AND condition

df[(df['salary']>5000) & (df['age']>25)]

  name  age  salary
1    B   30    6000
3    D   28    7000

In [100]:
## OR condition

df[(df['salary']>6500) | (df['age']<25)]

  name  age  salary
2    C   22    4500
3    D   28    7000

In [101]:
## NOT Condition

df[~(df['salary']<=5000)]

  name  age  salary
1    B   30    6000
3    D   28    7000

In [ ]:
## df.loc[ row_condition , "name" ]

## So Pandas selects rows where the value is True.

## df["salary"] > 5000

## 0    False
## 1    True
## 2    False
## 3    True

## This is called a Boolean Series.

## Row 1 → True
## Row 3 → True